## H2 Test Database creds
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql = true

## sql
SQL_ADD_CATEGORY_ONE=INSERT INTO category(category_name, category_desc) VALUES('Pizza', 'Any Pizza, Any Toppings')
SQL_ADD_CATEGORY_TWO=INSERT INTO category(category_name, category_desc) VALUES('Burger', 'Best Value')
SQL_ADD_USERS_ONE=INSERT INTO users (first_name, last_name, gender, languages, email_id, country, password, role) \
VALUES('test', 'test', 'male', ARRAY['Java', 'C', 'C#'], 'test@abc.com', 'USA', '123456', 'Admin')
SQL_DELETE_CATEGORY=DELETE FROM category
SQL_RESET_CATEGORY=ALTER TABLE category ALTER COLUMN category_id RESTART WITH 1
SQL_DELETE_ITEM=DELETE FROM item
SQL_RESET_ITEM=ALTER TABLE item ALTER COLUMN item_id RESTART WITH 1
SQL_DELETE_USERS=DELETE FROM users
SQL_RESET_USERS=ALTER TABLE users ALTER COLUMN user_id RESTART WITH 1


#jdbc.execute("DELETE FROM users");
#		jdbc.execute("ALTER TABLE users ALTER COLUMN user_id RESTART WITH 1");
#		
#		jdbc.execute("DELETE FROM category");
#		jdbc.execute("ALTER TABLE category ALTER COLUMN category_id RESTART WITH 1");
#		
#		jdbc.execute("DELETE FROM item");
#		jdbc.execute("ALTER TABLE item ALTER COLUMN item_id RESTART WITH 1");
#		jdbc.execute("DELETE FROM category");
#		jdbc.execute("ALTER TABLE category ALTER COLUMN category_id RESTART WITH 1");
#		
#		jdbc.execute("DELETE FROM users");
#		jdbc.execute("ALTER TABLE users ALTER COLUMN user_id RESTART WITH 1");

##Authentication
#jdbc.execute("INSERT INTO users (first_name, last_name, gender, languages, email_id, country, password, role) "
#				+ "VALUES('test', 'test', 'male', ARRAY['Java', 'C', 'C#'], 'test@abc.com', 'USA', '123456', 'Admin')");
#	}
##category
#"INSERT INTO category(category_name, category_desc) VALUES('Pizza', 'Any Pizza, Any Toppings')"
##Item
#jdbc.execute("INSERT INTO category(category_name, category_desc) VALUES('Pizza', 'Any Pizza, Any Toppings')");	
#		jdbc.execute("INSERT INTO category(category_name, category_desc) VALUES('Burger', 'Best Value')");
##uses
#jdbc.update("INSERT INTO users (first_name, last_name, gender, languages, email_id, country, password, role) VALUES(?,?,?,?,?,?,?,?)", 
#				"test","test","male", new String[]{"Java", "C", "C#"}, "test@abc.com", "USA", "123456", "Admin");
#	}