## H2 Test Database creds
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql = true

## sql
SQL_ADD_CATEGORY_ONE=INSERT INTO category(category_name, category_desc) VALUES('Pizza', 'Any Pizza, Any Toppings')
SQL_ADD_CATEGORY_TWO=INSERT INTO category(category_name, category_desc) VALUES('Burger', 'Best Value')
SQL_ADD_USERS_ONE=INSERT INTO users (first_name, last_name, gender, languages, email_id, country, password, role) \
VALUES('test', 'test', 'male', ARRAY['Java', 'C', 'C#'], 'test@abc.com', 'USA', '123456', 'Admin')
SQL_DELETE_CATEGORY=DELETE FROM category
SQL_RESET_CATEGORY=ALTER TABLE category ALTER COLUMN category_id RESTART WITH 1
SQL_DELETE_ITEM=DELETE FROM item
SQL_RESET_ITEM=ALTER TABLE item ALTER COLUMN item_id RESTART WITH 1
SQL_DELETE_USERS=DELETE FROM users
SQL_RESET_USERS=ALTER TABLE users ALTER COLUMN user_id RESTART WITH 1
SQL_DELETE_ITEM_ORDER_DETAILS=DELETE FROM item_order_details
SQL_RESET_ITEM_ORDER_DETAILS=ALTER TABLE item_order_details ALTER COLUMN item_order_details_id RESTART WITH 1
SQL_DELETE_ITEM_ORDER=DELETE FROM item_order
SQL_RESET_ITEM_ORDER=ALTER TABLE item_order ALTER COLUMN order_id RESTART WITH 1

