spring.application.name=ecommerceproject02282026self
#database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerceproject02282026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.config.import=optional:file:.env[.properties]
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.security.user.password=Test12345_
#server listening to port
server.port=8185

security.jwt.secret-key=TvsULYBUMOzPVsSV2iTpDMrPmQ52WSe3g98MSjswg8V
# 1h in millisecond
security.jwt.expiration-time=3600000
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}